development:
  adapter: mysql2
  host: localhost
  database: bius_infosystem_development
  username: root

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: pg
  encoding: utf8
  host: db.kset.org 
  database: bius-infosystem
  username: bius-infosystem
  password: w00t
