development:
  adapter: postgresql
  encoding: utf8
  database: bius-infosystem-dev
  username: bius-infosystem
  password: Eevo5oop
  host: db.kset.org 

production:
  adapter: postgresql
  encoding: utf8
  database: bius-infosystem-prod
  username: bius-infosystem
  password: Eevo5oop
  host: db.kset.org 
