development:
  adapter: postgresql
  encoding: unicode
  database: bius-infosystem-dev
  username: bius-infosystem
  password: Eevo5oop
  host: db.kset.org 

production:
  adapter: postgresql
  encoding: unicode
  database: bius-infosystem-prod
  username: bius-infosystem
  password: Eevo5oop
  host: db.kset.org 

test:
